### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by slavserver** [etclabscore/go-etchash#1]
hello ... remember ubiqhash and how it fell in price ... you would like only video cards to be mining ... and what, your coin went to the bottom ...
Now imagine, you are doing etchash, you are planning to attract 3 gigabytes, 4 gigabytes of video cards to mining .... and what's the point? these video cards, compared to modern ones, consume more electricity ... a modern 8 gigabyte card consumes 70 watts .... while older cards consume 150-180 watts of energy ... you as ubiqhash destroy the coin .... you were asked - pirlguard

_______________________

привет... вспомните ubiqhash и как он упал в цене..... вы, хотели, что бы майнингом занимались только видеокарты..... и что? - Ваша монета ушла на дно....
а теперь представьтье, вы делаете etchash , вы планируте привлечь к майнингу видеокарты 3 гигабата, 4 гигабайта.... а в чем смысл? эти видео карты, по сравнению с современныменными, потребляют больше электричичесва.....  современная карта на 8 гигабайт, потребляет 70 ватт....  в то время как более древние карты потребляют 150- 180 ватт энергиии....,  вы, как ubiqhash  уничтожите монету.... вам было предложено - pirlguard

**Comment by nenastupi** [comment]
+1
against algorithm change

**Comment by Rom1kz** [comment]
I'm sure there are many ways to reduce the DAG size without changing the algorithm
so I am against changing the algorithm
you are going to kill ETC

**Comment by slavserver** [comment]
+1

**Comment by slavserver** [comment]
what you do is the death of a coin -(

**Comment by Konstantin35** [comment]
No one wanted to attract miners they wanted to get away from the attack 51%

**Comment by q9f** [comment]
please redirect your concerns to the official spec discussion

https://github.com/ethereumclassic/ECIPs/issues/368
